#!/usr/bin/env python
"""Generate the tiny synthetic reference + read fixtures for oxo-flow-rnaseq.

Deterministic (fixed seed). Produces:
  reference/genome.fa       chr1 (~140kb) + chr2 (~5kb)
  reference/transcripts.fa  one transcript per gene ({gene}_t1), the
                            concatenated exon sequences (reverse-complemented
                            for '-' strand genes) — Salmon alignment-mode
                            transcriptome input
  reference/genes.gtf       60 genes on chr1 (protein_coding/rRNA/lncRNA mix)
                            with 2-3 exons each; gene_biotype attributes
  reference/gene.bed        12-column BED of the same exons (RSeQC input)
  reference/chrom_sizes.txt UCSC chrom.sizes (sorted by size, descending)
  reference/star_index/     README only (STAR index is a placeholder input;
                            build one for real runs)
  raw/<S>_R1/R2.fastq.gz    1200 151 bp read pairs x 6 samples with 3' TruSeq
                            adapters on a subset, spliced reads spanning gene
                            junctions, and some duplicated pairs

The reads are sampled from the genome so a STAR index built from genome.fa can
align them; they are NOT biologically realistic.
"""
import gzip
import os
import random

HERE = os.path.dirname(os.path.abspath(__file__))
REF = os.path.join(HERE, "reference")
RAW = os.path.join(HERE, "raw")
SEED = 42
ADAPTER = "AGATCGGAAGAGCACACGTCTGAACTCCAGTCA"  # TruSeq adapter (R1 3')
READ_LEN = 151   # nf-core test-data length: the STAR index is built with the default sjdbOverhang=100, so reads must be > overhang+1 (live: 100bp reads got a negative anchor and all 400 were classified "too short")


def rand_seq(rng, n):
    return "".join(rng.choice("ACGT") for _ in range(n))


def build_genome(rng):
    chr1 = rand_seq(rng, 4200000)  # the 60-gene cursor ends ~216kb (live: reads past the genome end came out empty)
    chr2 = rand_seq(rng, 5000)
    return chr1, chr2


def reverse_complement(seq):
    return seq.translate(str.maketrans("ACGT", "TGCA"))[::-1]


# Genes on chr1: (name, biotype, strand, [(exon_start, exon_end), ...]).
# 60 genes so DESeq2's dispersion fit has enough support (live: 4 genes
# x 6 samples still failed estimateDispersionsFit).
BIOTYPES = ["protein_coding", "protein_coding", "protein_coding", "rRNA", "lncRNA"]
GENES = []
_cursor = 0
for _i in range(60):
    _n_exons = 3 if _i % 3 else 2
    _exons = []
    for _e in range(_n_exons):
        _start = _cursor + 200 + _e * 600
        _exons.append((_start, _start + 400))
        _cursor = _start + 400
    GENES.append((f"GENE{_i + 1}", BIOTYPES[_i % len(BIOTYPES)],
                  "+" if _i % 2 == 0 else "-", _exons))
    _cursor += 60000  # intergenic gap (100x spread: contiguous aligners like bowtie2
    # otherwise collide on the packed genes — live: 64% picard duplicates, dupRadar density NaN)


def write_reference(chr1, chr2):
    os.makedirs(REF, exist_ok=True)
    with open(os.path.join(REF, "genome.fa"), "w") as f:
        for name, seq in (("chr1", chr1), ("chr2", chr2)):
            f.write(f">{name}\n")
            for i in range(0, len(seq), 80):
                f.write(seq[i:i + 80] + "\n")

    with open(os.path.join(REF, "genes.gtf"), "w") as f:
        f.write('##generated by generate_fixtures.py (synthetic)\n')
        for name, biotype, strand, exons in GENES:
            tstart = exons[0][0]
            tend = exons[-1][1]
            common = (f'gene_id "{name}"; gene_name "{name}"; transcript_id "{name}_t1"; '
                      f'gene_biotype "{biotype}"; transcript_biotype "{biotype}";')
            f.write(f'chr1\tsynthetic\ttranscript\t{tstart + 1}\t{tend}\t.\t{strand}\t.\t{common}\n')
            for i, (es, ee) in enumerate(exons, start=1):
                f.write(f'chr1\tsynthetic\texon\t{es + 1}\t{ee}\t.\t{strand}\t.\t{common}\n')

    with open(os.path.join(REF, "gene.bed"), "w") as f:
        for name, biotype, strand, exons in GENES:
            chrom = "chr1"
            cstart = exons[0][0]
            cend = exons[-1][1]
            blocks = ",".join(str(e - s) for s, e in exons)
            starts = ",".join(str(s - cstart) for s, e in exons)
            rgb = {"protein_coding": "205,0,0", "rRNA": "0,205,0", "lncRNA": "0,0,205"}[biotype]
            f.write(f"{chrom}\t{cstart}\t{cend}\t{name}\t0\t{strand}\t{cstart}\t{cend}\t{rgb}\t"
                    f"{len(exons)}\t{blocks}\t{starts}\n")

    sizes = [("chr1", len(chr1)), ("chr2", len(chr2))]
    sizes.sort(key=lambda kv: -kv[1])
    with open(os.path.join(REF, "chrom_sizes.txt"), "w") as f:
        for name, size in sizes:
            f.write(f"{name}\t{size}\n")

    # transcripts.fa: one transcript per gene, concatenated exons; reverse
    # complement for '-' strand genes so the FASTA holds the spliced mRNA.
    with open(os.path.join(REF, "transcripts.fa"), "w") as f:
        for name, biotype, strand, exons in GENES:
            seq = "".join(chr1[s:e] for s, e in exons)
            if strand == "-":
                seq = reverse_complement(seq)
            f.write(f">{name}_t1\n")
            for i in range(0, len(seq), 80):
                f.write(seq[i:i + 80] + "\n")


def fragment_sequence(chr1, exons, rng, spliced=True):
    """Return a transcript-derived 2xREAD_LEN fragment sequence (R1, R2)."""
    if len(exons) > 1 and spliced and rng.random() < 0.3:
        # Spliced pair: choose a junction; R1 spans it.
        junction_i = rng.randrange(len(exons) - 1)
        exon_a = exons[junction_i]
        exon_b = exons[junction_i + 1]
        pre = rng.randrange(10, 26)          # bases read from exon_a's end
        post = READ_LEN - pre                 # bases read from exon_b's start
        r1 = chr1[exon_a[1] - pre: exon_a[1]] + chr1[exon_b[0]: exon_b[0] + post]
        # Mate: from exon_b (downstream), reverse-complemented — paired
        # reads are FR oriented (live: forward-forward mates made STAR
        # classify every pair as 'too short').
        pos = exon_b[0] + rng.randrange(0, max(1, exon_b[1] - exon_b[0] - READ_LEN))
        r2 = reverse_complement(chr1[pos:pos + READ_LEN])
        return r1, r2
    # r2 ends at start+120+READ_LEN, so the window needs only
    # READ_LEN+120 bp of exon — the old bound (2*READ_LEN+100) left a
    # 1-base range and every unspliced read of a gene started at the
    # same base (live: 64% picard duplicates, dupRadar bandwidth NaN).
    start = rng.randrange(exons[0][0], max(exons[0][0] + 1, exons[0][1] - READ_LEN - 120))
    r1 = chr1[start:start + READ_LEN]
    r2 = reverse_complement(chr1[start + 120: start + 120 + READ_LEN])  # ~120 bp insert
    if len(r1) < READ_LEN or len(r2) < READ_LEN:
        start = exons[0][0]
        r1 = (chr1[start:start + READ_LEN] + rand_seq(rng, READ_LEN))[:READ_LEN]
        r2 = reverse_complement((chr1[start + 120: start + 120 + READ_LEN] + rand_seq(rng, READ_LEN))[:READ_LEN])
    return r1, r2


def write_reads(chr1, chr2):
    os.makedirs(RAW, exist_ok=True)
    # 6 samples like the nf-core test profile — DESeq2's dispersion fit
    # needs enough samples (live: estimateDispersionsFit failed on 2).
    for sample in ("S1", "S2", "S3", "S4", "S5", "S6"):
        rng = random.Random(SEED + sum(ord(c) for c in sample))  # hash() is PYTHONHASHSEED-salted — not reproducible across runs
        r1s, r2s = [], []
        for _ in range(1200):
            gene = rng.choice(GENES)
            # Unique fragments only: 1200 random draws over 400bp exons
            # collided massively (64% picard duplicates live) and killed
            # dupRadar's density plot (bandwidth NaN).
            for _attempt in range(50):
                r1, r2 = fragment_sequence(chr1, gene[3], rng)
                if r1 not in r1s:
                    break
            if gene[2] == "-":
                # the '-' transcript's 5' end = rc of the genome's
                # downstream region (= the FR mate), its 3' end = rc of
                # the upstream region
                r1, r2 = r2, reverse_complement(r1)
            # 3' adapter on a subset (trimgalore will trim it)
            if rng.random() < 0.25:
                r1 = r1[:READ_LEN - 20] + ADAPTER[:20]
            if rng.random() < 0.25:
                r2 = r2[:READ_LEN - 20] + ADAPTER[:20]
            r1s.append(r1)
            r2s.append(r2)
        # A few duplicated pairs so DupRate/dupRadar have signal
        for i in range(20):
            r1s[-(i + 1)] = r1s[i]
            r2s[-(i + 1)] = r2s[i]
        qual = "I" * READ_LEN
        with gzip.open(os.path.join(RAW, f"{sample}_R1.fastq.gz"), "wt") as f1, \
             gzip.open(os.path.join(RAW, f"{sample}_R2.fastq.gz"), "wt") as f2:
            for i, (r1, r2) in enumerate(zip(r1s, r2s), start=1):
                f1.write(f"@{sample}_{i}\n{r1}\n+\n{qual}\n")
                f2.write(f"@{sample}_{i}\n{r2}\n+\n{qual}\n")


def main():
    rng = random.Random(SEED)
    chr1, chr2 = build_genome(rng)
    write_reference(chr1, chr2)
    write_reads(chr1, chr2)
    with open(os.path.join(REF, "star_index", "README.md"), "w") as f:
        f.write("# STAR index (placeholder)\n\n"
                "The STAR index is an upstream input artifact (PREPARE_GENOME is not\n"
                "ported). Build one for your genome before running, e.g.:\n\n"
                "    STAR --runMode genomeGenerate --genomeDir star_index \\\n"
                "        --genomeFastaFiles genome.fa --sjdbGTFfile genes.gtf \\\n"
                "        --runThreadN 8\n\n"
                "and point `config.star_index` at the directory containing the\n"
                "`SA`, `SAindex`, `genomeParameters.txt` etc. files.\n")
    print("fixtures written to", REF, "and", RAW)


if __name__ == "__main__":
    main()
